# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "o+zYPsNPeotYIg0DTOwUsIluDiKnSZ3F4BcFW5qvUvJ2Z6M8bW9jL01hQHCQGwZ/1wFctXEagGpwr5gw754GIpS8p+5fQqTUBxgqDk/hhYi+mcznNeKUrBzvGLb54rWhf4iQvO8Kh/fUguoBKx3B8iSiwcaDUxxF0b5CQW9bz8/QVTNduSf7qorWweRxARlbUo+xThohR6J78nnR+CXZTADjkAbd0oQUcnP6ej8S0zbqtw7yfSLgA2YU6OgAxkJCcHfAZedCAXmUoPW+OZKLtNTEzT+vdS+JI2TL/ASvi4bqBYYcSyNeqDKl+qv1MWQE2JXTY2HUCHV7zCzEFJF7CW0eWiwyglTXEV+VTeM2hao0XQ9qngdgfNah7TW2tF9sCmzYf0q536UWjRj4MJzi9vTAQmEtNHsGB3vOkObdyYrV1dH1dbdS2BVggmsNrQCNWbIuxQcqf8qzGKNORyYnNwWqIjsPhALj/5iOBrD0RQZmhSirYva4hHV7onIlxJl2Uuop96NcllSC7XQZ+DCioV/zIdiznvGdz4FB56JxWk2EYxSAn2zzS3TpkY9z21aj8EYUxKQeqriMDfhlBy5MYeKGiZqkSJFY37RNITPMBXh+yAp+DBWC9FOnm1D+eeDc7R8TUxRvJMr0EGT9RFJQ7rh4SeFlUr8tnUivPBPqLtE="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
