appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: kSs1fI8SCHpNdKXI1KOI6kCGCe689NWGWz9PjzHkCzZ46HK4VYVORw8bvoTTattItfNRnen07Tx7mDw11We3RD4vuuvmyzsIU7Agf72VIKjqvvGHvH0frCwjrvGUrBI5xVNDbQfOtkAZj1QIJJzLRcsvHM1JnCjVmqisxFYanjr5MIz8FV6TRENuBaTDfOJ25AqtWBrq+TJJthJNhGi/NRz5pKrywnLLpFKTnZq/4OJpgAV4p/PAQEcwEIj2tSCNgUvxWsLoVtnMesb+MvyL0KoBptAfJutcBJ4AQ34RP7SQfe51a+C27n9zz2sp7Y845KIbsEhfCXu6UI3HZAxZzOqyI0nBEDomfZiKhZIOw5iyx+56oru8h0B9thbdq54aYuKgC09lPstxk20T+utB4jGu5uCHui68UaVv80I9ep9BCKLfRDLfX/kbKyl6WB8BP/OZj6G43LVpogO61G5Zh+agiF5jZDUSLwf/42tvc/DVSpTrF0Q6+p+rpSOdP9YcqcTBpcF3FPxS7ZBh4kvGFdxLuqu2peNF4B31gKbTIcX2jjFDl7I3PpfsaXCVPE/RFIyXN/4JxKw1uUnUzo+bJct538RLTEyPEHNKmmCKs3GheGe1SlmPCMjjz0oP4OK+qML9xzvakq1w2/Q1NUeiqjBe64TDQM3bmKLzWoTit60=}
