travis:
  secure:
    BINSTAR_TOKEN: OJbO2sgepL7uI8jNFqNrMK94wZPSi8Wz4Ef8UqgkX7zgM1MPLupK3jRAX5/y1he9cXNTqu/L8UIoG/LyWOc6drRorp9ImSBhnSXsBtSZrWefapvfg+CDHwOgSAT8c36n5YXMXV6XJkOALk0lj9dD+YocX7L14S5qUzFHMBiJ5TfH5jDIcX7Ucm8CNOvsZTjCgR8vuBHWsSaVT0PrMaM8N9EWXuxm1oKkAQAkDtea1SGGJEDFxyEzLTbh84jiumydAwrk4A0u3SrBxMRyd30MojmQYVybvvVgl3I3FnY0UJ7YbbaM6cpS1mDvmMK6OwSRNduMZHPBWzlo3Ul4MwLpGlfUts6k49jAWNFfKIba3NyLsMlcAWq7e0Yj4cj0h/fyEJklBOeGKVYNDsMLV/ubnJdpVvU74EK4O14PGIfTKlM1zGc7MJCTM9uud/5Ump8eaPRn4pDAeqZfFJqoXHU8zzlS8mo72oVVQgNz7JHqUJpDW10AhJyWc36GVldrpAd12Gu6i5sj7v1fhbGMJiRnFd+OfVI9yahXzvNH8fVn0b5ltLN8eZ5GHPV3qgYXiyej2rMiiSQkX/jO5M0kvKQnICwmA2cBrZ4Nl1B43xf3Vcdmx88f4DiHcoy+1QqBnd7U9aytF733sS1mGDLDKP0OizqBLslH8E2tGuglkZ4FWIs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
