travis:
  secure:
    BINSTAR_TOKEN: o+zYPsNPeotYIg0DTOwUsIluDiKnSZ3F4BcFW5qvUvJ2Z6M8bW9jL01hQHCQGwZ/1wFctXEagGpwr5gw754GIpS8p+5fQqTUBxgqDk/hhYi+mcznNeKUrBzvGLb54rWhf4iQvO8Kh/fUguoBKx3B8iSiwcaDUxxF0b5CQW9bz8/QVTNduSf7qorWweRxARlbUo+xThohR6J78nnR+CXZTADjkAbd0oQUcnP6ej8S0zbqtw7yfSLgA2YU6OgAxkJCcHfAZedCAXmUoPW+OZKLtNTEzT+vdS+JI2TL/ASvi4bqBYYcSyNeqDKl+qv1MWQE2JXTY2HUCHV7zCzEFJF7CW0eWiwyglTXEV+VTeM2hao0XQ9qngdgfNah7TW2tF9sCmzYf0q536UWjRj4MJzi9vTAQmEtNHsGB3vOkObdyYrV1dH1dbdS2BVggmsNrQCNWbIuxQcqf8qzGKNORyYnNwWqIjsPhALj/5iOBrD0RQZmhSirYva4hHV7onIlxJl2Uuop96NcllSC7XQZ+DCioV/zIdiznvGdz4FB56JxWk2EYxSAn2zzS3TpkY9z21aj8EYUxKQeqriMDfhlBy5MYeKGiZqkSJFY37RNITPMBXh+yAp+DBWC9FOnm1D+eeDc7R8TUxRvJMr0EGT9RFJQ7rh4SeFlUr8tnUivPBPqLtE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
